### PR TITLE
Sets up react + express + postgresql + logo

### PR DESCRIPTION
**Pull request by ameliejyc**
Relates #2 #3

### CODE REVIEW

**Comment by Jwhiles** [comment]
image
looks GREAT

**Comment by astroash** [comment]
I cannot get this working on my local 😿
dickdown

**Comment by ameliejyc** [comment]
Hey mate there's two servers going on, the express one (localhost:3001) and the one created by create-react-app (localhost:3000). Express is set up in the root and React is set up in a folder called `client`. When we're using our backend we'll run `npm start` in the root for express and then in a new tab cd to `client` and run `npm start` again for react. Then localhost:3000 will work with the backend :) but for now given we don't have a backend you can just `npm start` within the client folder. I put some notes in the readme about it :)

**Review by astroash — APPROVED** [review]
🍆

**Pull request merged**
